<a href="https://colab.research.google.com/github/rainehulse/Statistics/blob/main/Hulse_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Lab 3

### Loops

In [1]:
for i in range(100):
    print(i) #creating a range of 100 numbers

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [2]:
for i in range(5,8):
    print(i)

5
6
7


In [3]:
for i in range(3):
    print( "Test Number: " , i ) #printing test numbers

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [4]:
def square(x):
    return x**2

In [5]:
square(5)

25

In [6]:
square(square(2))

16

In [7]:
square(square(square(2)))


256

In [8]:
square(123456)

15241383936

In [9]:
square(square(5))

625

In [10]:
def add_two(x):
    return x+2

In [11]:
add_two(5)

7

In [12]:
square(add_two(5))

49

### Logical Branching

In [13]:
choice = "apple" #making a variable/option

In [14]:
if choice == "apple":
  print("You choose apples.")
else:
  print("You did not choose apples.") #output

You choose apples.


In [15]:
choice = "orange" #making another variable

In [16]:
if choice == "apple":
  print("You choose apples.")
else:
  print("You did not choose apples.") 

You did not choose apples.


In [17]:
choice = "apple"

In [18]:
if choice == "apple":
  print("You choose apples.")
  print("Thank you, shop again!")
  print(2**123)
elif choice == "orange":
  print("You choose oranges.")
  print("Thank you, shop again!")
else:
  print("You did not choose apples or oranges.")
  print("Thank you, shop again!") #making multiple options for the output

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [19]:
choice = input("Please enter your choice (i.e. apple): ") #input being a sentence with output and the full sentence

Please enter your choice (i.e. apple): 


In [20]:
choice #displays what was written in choice

''

In [21]:
if choice == "apple":
  print("You choose apples.")
elif choice == "oranges":
  print("You choose oranges.")
else:
  print("You did not choose apples or oranges.") #giving options for the output

You did not choose apples or oranges.


#### Coins

In [22]:
import numpy as np

In [23]:
np.random.random() #random number generator

0.818953902556998

In [24]:
np.random.random() > 0.5

False

In [25]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [26]:
flip_coin() #output from flip coin (can be heads or tails)

Tails


### Graphics Output

In [27]:
from IPython.core.display import display, HTML

In [28]:
display(HTML('<h1>Hello, world!</h1>'))

In [29]:
def coin():
  return np.random.randint(2)

In [30]:
coin() #output

1

In [31]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) #front side of quarter (heads)

In [32]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg' #naming heads and tails

In [33]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [34]:
show_img(heads)

In [35]:
show_img(tails)

In [36]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [37]:
flip_coin()

In [38]:
for i in range(5):
    flip_coin()

In [39]:
#@title Coin Flip
if coin():
  show_img(heads)
else:
  show_img(tails) #making just an image

### Cards

In [ ]:
def shuffle(x):
  for i in range(len(x)-1,0,-1):
    j = np.random.randint(0,i+1)
    x[i],x[j] = x[j],x[i]
    #print(j,x)
  return x #multiple random number generator

In [ ]:
a = np.arange(52) #52 different random numbers

In [ ]:
shuffle(a) #output created for cards

array([44,  8, 45, 48, 28, 13,  3, 10, 12, 29, 23, 42,  6, 15,  0, 47, 21,
       36, 46, 51, 49, 32, 40, 27, 37,  9, 34,  4, 30,  5, 24, 22, 20,  7,
       11, 14, 25,  2, 31, 19, 18, 33, 16,  1, 41, 38, 39, 17, 35, 50, 43,
       26])

In [ ]:
np.random.permutation(52)

### Speed Test

In [ ]:
%%timeit
shuffle(a) #shuffle 52 random numbers

169 µs ± 4.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%%timeit
np.random.permutation(52) 

3.4 µs ± 196 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
import numpy as np

In [ ]:
np.random.permutation(52) #mixed up

array([51,  2, 17, 20, 19, 44,  8, 37,  0, 24, 12,  6,  1,  3, 25,  4, 34,
       36, 16, 10, 27, 50, 47, 28, 33, 42, 41, 45,  5, 40, 26, 32, 46, 38,
       31, 35, 49, 39, 23, 13, 29, 30, 21, 14, 11, 48, 43, 15, 18,  9,  7,
       22])

In [ ]:
cards = np.random.permutation(52)

In [ ]:
cards #different 

array([42, 25, 13, 12, 34, 27, 39, 24,  8, 32, 43, 48, 50,  4, 41, 49,  6,
       29,  7, 31, 26, 36, 45, 38,  1, 10, 46, 35, 20,  9, 47, 21, 23, 14,
       15, 22, 16, 33, 19, 18,  5, 30,  2, 11, 17,  3, 28,  0, 51, 37, 44,
       40])

In [ ]:
cards[0] #one of the ouputs

42

In [ ]:
cards[1] #one of the ouputs

25

In [ ]:
cards[2] #another output

13

In [40]:
np.arange(52).reshape(4,13) #written as numbers 0-12 and cont.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [41]:
np.arange(52).reshape(4,13)%13 #written as only 0-12

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [42]:
np.arange(52).reshape(4,13)//13 #wrtitten in 4 rows

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [43]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King'] #creates the deck with suits and names

In [44]:
def card_name(card_number):  
  suit = card_number//13
  name = card_number%13
  return names[name] + " of " + suits[suit] #code to make the deck

In [45]:
card_name(0) #beginning

'Ace of Clubs'

In [46]:
card_name(51) #end

'King of Diamonds'

In [47]:
cards = np.random.permutation(52)

In [67]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1]) #setting variables (card in deck) to a specific card

In [68]:
top_of_deck, second_card_in_deck, last_card_in_deck #outout

('Ten of Clubs', 'Four of Diamonds', 'Jack of Clubs')

In [69]:
for i in range(5):
    print(card_name(cards[i])) #flipping 5 random cards

Ten of Clubs
Four of Diamonds
Nine of Hearts
King of Diamonds
Seven of Clubs


In [70]:
for i in range(15):
    print(card_name(cards[i])) #flipping 15 random cards

Ten of Clubs
Four of Diamonds
Nine of Hearts
King of Diamonds
Seven of Clubs
Nine of Clubs
Seven of Diamonds
Four of Spades
Eight of Hearts
Three of Diamonds
Ace of Diamonds
King of Hearts
Two of Clubs
Seven of Spades
Eight of Clubs


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [71]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png" #setting pictures to the variables

In [72]:
suit = ['d','h','s','c']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']  #setting suits and numbers

In [74]:
i = np.random.randint(4)
j = np.random.randint(13) 

In [73]:
i,j #randomed output

(14, 8)

In [76]:
suit[i] #random suit

'h'

In [77]:
card[j] #random card

'k'

In [58]:
from IPython.core.display import display, HTML

In [59]:
def show_img(img):
  display(HTML('<img src=' + img + '>')) 

In [60]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [78]:
show_img(img) #setting images to cards, output

In [79]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j] 

In [81]:
card_image(3) #random set of suit and number

'd4'

In [82]:
img = card_url_head + card_image(3) + card_url_tail

In [83]:
show_img(img)

In [84]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img) #output image of all 52 cards